### ISSUE TITLE
APKs at releases not signed

### ISSUE THREAD

**Issue by IzzySoft** [shorthouse/CoinWatch#1]
Could you please provide *signed* APKs at your releases? At least the one for the currently latest release is not signed, and thus cannot be installed (not everyone is able to self-sign – and not everyone can use PlayStore). Thanks in advance!

**Comment by shorthouse** [comment]
Hi IzzySoft,

Thanks for raising this issue. I have amended release 1.1.2 (latest) to include a signed release APK instead, and this should now work on your device.

Please do let me know if you have any other issues or improvements for CoinWatch!

**Comment by IzzySoft** [comment]
Thanks! Not exactly *my* device, but…
![image](https://github.com/shorthouse/CoinWatch/assets/6781438/a6e3e678-8d35-46b1-aa8b-eb0a133dea13)

Becoming [visible here](https://apt.izzysoft.de/packages/dev.shorthouse.coinwatch/) with the next sync around 6 pm UTC. If you want you can then [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to accompany the lonely PlayStore one and point it there :wink: Updates are usually pulled automatically within 24h of your making the APK available at a new release – provided the signature matches. This makes your app available to those using an F-Droid client (e.g. as they don't trust or cannot access PlayStore, as indicated initially). Hope you like it that way!

(PS: No worries about the AntiFeature – all coin-watching APIs seem to have it. There's simply no "libre" API available. Making it visible is for transparency – same as the library listing you will find there when scrolling down, plus the results from the VT scan)

**Comment by shorthouse** [comment]
Happy for this to go ahead, as it's always good to have multiple options to download open-source Android apps 😊

**Comment by IzzySoft** [comment]
That's the idea, yes :smiley: And using an [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) makes it easier for those without PlayStore to get updates in a timely member (without having to check Github releases manually) plus having an additional "security and transparency" layer (due to the [checks performed in my repo](http://apt.izzysoft.de/fdroid/index/info#security) – [F-Droid](https://f-droid.org/) has even more of them as they build from source and thus scan that as well). A clear win I'd say :star_struck:
