### ISSUE TITLE
IzzyOnDroid version out of date

### ISSUE THREAD

**Issue by OfficialMuffin** [shorthouse/CoinWatch#14]
Please could the ~~Fdroid~~ IzzyOnDroid version be updated to 1.2.9 as the app is no longer working on version 1.2.5.1

**Comment by G-i-o** [comment]
Yes. The current version on the F-Droid repo is outdated, thus no API update.

Also, if I may suggest, to add a cryptocurrency address in the About section, so those willing, can donate to cover the expenses for the API etc.

Keep up the good work!

**Comment by OfficialMuffin** [comment]
Apologies, I downloaded this app using  Droid-ify that has the IzzyOnDroid repos. I changed the title accordingly.

**Comment by shorthouse** [comment]
Thank you both for creating this issue - unfortunately I have made the difficult decision to only support CoinWatch on the Play Store going forward. I have much less time to devote to this app now and I wanted to simplify things by consolidating the user base and reducing my required workload when publishing a new version.

Please feel free to download the app from the Play Store. Alternatively, you can generate and use your own API key by following these steps:
1. Generate an API key from the [CoinRanking API](https://developers.coinranking.com/api/documentation). The free tier currently gives you 5,000 API calls a month.
2. Clone the project, create a file named `apikey.properties` in the top-level folder of the project
3. Paste your API key in the `apikey.properties` file  in the following format `API_KEY="xxx"` where xxx is replaced with your full key (keep the double quotes)
4. Generate an APK / AAB file for the project and install this on your Android device

I may stop paying for the API costs in the future, at which point the app will stop working completely. Creating and using your own API key ensures that you will always be able to use the app, as long as CoinRanking continues service.

Let me know if you have any questions about the above 😊

**Comment by G-i-o** [comment]
Thank You @shorthouse . Sad but understandable.

I hope sb with some experience with the F-Droid repos can chip in and help as maintainer sometimes in the future. For those acquinted with the process should not take too much time, given the size of the project and rare critical updates.

Meanwhile, thank you for providing alternative instructions.

Keep up the good work.

**Comment by IzzySoft** [comment]
> Thank you both for creating this issue - unfortunately I have made the difficult decision to only support CoinWatch on the Play Store going forward. I have much less time to devote to this app now and I wanted to simplify things by consolidating the user base and reducing my required workload when publishing a new version.

That's unfortunate. I've just noticed all APKs are gone from your releases, which is where IzzyOnDroid took them from. With no updates possible, it's more or less dead at IoD then – so shall we remove it there, or do you plan to bring the APKs back?

**Comment by shorthouse** [comment]
Hi @IzzySoft, the APK removals were part of this, as the app is now only available through Google Play with no plans to bring them back. As such please remove it from IoD

**Comment by IzzySoft** [comment]
Done, effective with the next sync around 7 pm UTC.
