### ISSUE TITLE
"Market change unavailable"

### ISSUE THREAD

**Issue by Playit3110** [shorthouse/CoinWatch#15]
When starting the app, i got this toast: "Market change unavailable"

**Comment by shorthouse** [comment]
Hi @Playit3110 

Thanks for raising this issue. The Market Change is the text at the top of the Market screen that states either "Market is up" or "Market is down". 

I have tested this functionality and it is working on my tests and my app. The API endpoint is also live and healthy. 

I would be suprised if you can fetch coin data but not the market change data, as the data all comes from the same provider.

Are you still facing this issue? If so let me know and I can help you troubleshoot it.

**Comment by Playit3110** [comment]
The issue is still there. Is there a way to get some logs or a logfile?

**Comment by shorthouse** [comment]
I would suggest killing the app completely and see if that resolves the issue. I am still unsure why all the other data can be fetched but not the market stats, and I haven't had this issue reported by any other users. I assume the "Market is up" or "Market is down" text is also missing?

**Comment by Playit3110** [comment]
Even killing the app didnt help and yeah the market is down or up is missing

**Comment by shorthouse** [comment]
Are you using the app downloaded from the play store? If so, your app data
should be backed up and you can try reinstalling. Your settings and
favourite coins should be saved.

**Comment by Playit3110** [comment]
I installed it over fdroid and izzyondroid repo

**Comment by Playit3110** [comment]
I think I know the reason. You updated thr API key, right? So the old one doesnt work anymore. Im still on 1.2.5.1 and since 1.2.9 is the new key used

**Comment by shorthouse** [comment]
You're right, the API key was updated, and any non Play Store versions of
the app were disabled as a result. The old Play Store versions of the app
also stopped working.

I implemented a 'force update' for the Play Store app, which supposedly
would force users to update before continuing to use the app. If you
haven't yet updated and this force mechanism didn't work for you, I would
try updating.

All the data in the app should be no longer working if this is case though,
not just the market state. Coin details and search should not load, and
pull refreshing on the market screen should display an error.

Let me know if updating fixes this for you 😊

**Comment by Playit3110** [comment]
Why is there no update on fdroid?

**Comment by shorthouse** [comment]
I understand the frustration, see this issue comment link for an
explanation -
https://github.com/shorthouse/CoinWatch/issues/14#issuecomment-2267632684

**Comment by Playit3110** [comment]
I see, makes sense. Thanks for your work by the way
