### ISSUE TITLE
cant start 1.1.2

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [shorthouse/CoinWatch#2]
i can install the app
**but i can not start 1.1.2**

Samsung S21 5G
Android 13

![photo1699819227](https://github.com/shorthouse/CoinWatch/assets/61406324/13a6add1-3c97-4551-985a-fe76da78f8c3)

**Comment by shorthouse** [comment]
Hi,

Thanks for creating this issue - I've confirmed that the APK in this GitHub release has stopped working.

I will take a look at this soon and resolve it. In the meantime, if you have access to the Google Play Store, you can download version 1.1.2 from there instead as this is the current latest version.

**Comment by shorthouse** [comment]
Hi @mondlicht-und-sterne I have now resolved this issue. Please let me know if any problems are still occurring on your device. Thanks again for raising this issue, your feedback helps make CoinWatch even better 😊
