### ISSUE TITLE
Add currency options

### ISSUE THREAD

**Issue by Wjxfi** [shorthouse/CoinWatch#3]

**Comment by shorthouse** [comment]
Hi @Wjxfi, thanks for your suggestion. The feature to choose currencies will be available in the next update. Is there a specific currency you would like to see?

**Comment by shorthouse** [comment]
Thanks for the suggestion - in the upcoming update that is in final release stages, you will be able to choose between USD, EUR, and GBP for the time being. Based on user feedback like this and as the app evolves, I will hopefully add more currencies later on.
