### ISSUE TITLE
Darkmode/Oled Black

### ISSUE THREAD

**Issue by DeadSecTr** [shorthouse/CoinWatch#4]
Add a Darkmode/Oled Black mode

**Comment by shorthouse** [comment]
Hi @DeadSecTr, thanks for raising this suggestion. 

The app itself is dark mode by default, so this is already implemented. As for an OLED black mode, unfortunately this would go against the design system of the app and require a full redesign. I'll close this issue for now, but I'll keep your OLED suggestion in mind if it is requested by more users.

**Comment by shorthouse** [comment]
Noted, thanks for the feedback @serrq
