### ISSUE TITLE
Drag & Drop 

### ISSUE THREAD

**Issue by DeadSecTr** [shorthouse/CoinWatch#5]
Posibilitiy to Drag & Drop the favs

**Comment by shorthouse** [comment]
Hi @DeadSecTr, thanks for the second suggestion. Drag and drop is something I've wanted to implement in the favourites screen for a while, but this functionality is not supported natively by Jetpack Compose just yet. You can see this feature in the public Compose roadmap linked [here](https://developer.android.com/jetpack/androidx/compose-roadmap), and once this is implemented in Compose I will look at adding it to the favourites screen.
