### ISSUE TITLE
Feature Request: Crypto Calculator

### ISSUE THREAD

**Issue by NearestWater262** [shorthouse/CoinWatch#6]
There is a feature I am wanting to see that is not ANYWHERE. It is very sad! I just want to be able to open up an open source price tracker app on my phone that can calculate some amount of BTC or ETH or any crypto, into USD/EUR or into other crypto coins. 

It is very inconvenient to go do this manually in a regular calculator or on a website. Plus, those amounts you are calculation on an online calculator like Coin Gecko can be easily tracked and are not private! And also it is slow process to do this.

This is a very easily functionality I think, and I would love to finally see a app on F Droid that can do this :( 
it is insufferable that no one has done this yet.

Thank you for your consideration! I can also make a small donation in XMR if you like >:)

**Comment by shorthouse** [comment]
Hi there,

While there are no plans to introduce a calculator at this time, this is an interesting idea and I will put it in our product roadmap.

Thanks for your suggestion!
