### ISSUE TITLE
The floating button covers the coin value

### ISSUE THREAD

**Issue by serrq** [shorthouse/CoinWatch#8]
OnePlus CPH2399
Android 14
CW 1.2.4

![1000108238](https://github.com/shorthouse/CoinWatch/assets/113377431/39df0a06-b5db-4100-8883-a7faf756f42e)

**Comment by shorthouse** [comment]
Hi @serrq, thanks for raising this issue. I see 2 solutions for this: either a space the size of the floating button at the bottom of the list, or to hide the floating button when you reach the bottom of the list. I'd be interested to get feedback on both, so do you have a preference towards either solution?

**Comment by shorthouse** [comment]
Resolved in latest release (1.2.6) by increasing padding around the button
